import React from 'react';

const PrivacyPolicy: React.FC = () => {
  return (
    <div className="bg-white p-6 max-w-4xl mx-auto text-gray-800">

      {/* Definitions and Key Terms Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">Definitions and Key Terms</h2>
        <p>
          To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, they are strictly defined as:
        </p>
        <ul className="list-disc pl-8">
          <li><strong>Cookie:</strong> Small amount of data generated by a website and saved by your web browser.</li>
          <li><strong>Company:</strong> Refers to [Your Company], the operator of the Site.</li>
          <li><strong>Country:</strong> Refers to [Country], where the company is located.</li>
          <li><strong>Customer:</strong> Refers to the company, organization, or person that signs up to use the [Company] service.</li>
          <li><strong>Device:</strong> Any internet-connected device such as a phone, tablet, computer, or any other device.</li>
          <li><strong>IP Address:</strong> Every device connected to the internet is assigned a number known as an IP address.</li>
          <li><strong>Personnel:</strong> Refers to individuals employed by [Company] or contracted to perform services on behalf of one of the parties.</li>
          <li><strong>Personal Data:</strong> Any information that directly or indirectly allows for the identification of a natural person.</li>
          <li><strong>Service:</strong> Refers to the service provided by [Company] as described in the relative terms.</li>
          <li><strong>Third-party Service:</strong> Refers to advertisers, contest sponsors, promotional and marketing partners.</li>
          <li><strong>Website:</strong> Refers to [Website], the site accessible at [URL].</li>
        </ul>
      </section>

      {/* What Information Do We Collect Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">What Information Do We Collect?</h2>
        <p>We collect information from you when you visit our website, register on our site, place an order, and subscribe to our newsletter. This includes the following:</p>
        <ul className="list-disc pl-8">
          <li>Name</li>
          <li>Email Address</li>
          <li>Phone Number</li>
          <li>Billing Address</li>
          <li>Payment Details</li>
        </ul>
      </section>

      {/* How Do We Use The Information We Collect Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">How Do We Use The Information We Collect?</h2>
        <p>A few of the ways we may use the information we collect include:</p>
        <ul className="list-disc pl-8">
          <li>To personalize your experience and support you better.</li>
          <li>To improve our website to better serve you.</li>
          <li>To process transactions efficiently and securely.</li>
          <li>To administer a promotion, survey, or other site feature.</li>
        </ul>
      </section>

      {/* Do We Share The Information We Collect Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">Do We Share The Information We Collect?</h2>
        <p>We do not sell, trade, or transfer to outside parties your Personally Identifiable Information unless we provide users with advance notice. This does not include website hosting partners and other parties who assist us in operating our website.</p>
      </section>

      {/* Where and When Is Information Collected Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">Where and When Is Information Collected?</h2>
        <p>We collect personal information when you provide it to us directly, when you visit our website, or through third-party platforms like social media accounts.</p>
      </section>

      {/* How Do We Use Your Email Address Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">How Do We Use Your Email Address?</h2>
        <p>
        By submitting your email address on our service, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective email. We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do not send unsolicited commercial emails, because we hate spam as much as you do. By submitting your email address, you also agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display custom advertising to specific people who have opted-in to receive communications from us. Email addresses submitted only through the order processing page will be used for the sole purpose of sending you information and updates pertaining to your order. If, however, you have provided the same email to us through another method, we may use it for any of the purposes stated in this Policy. Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">Could my information be transferred to other countries?</h2>
        <p>
        By submitting your email address on our service, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective email. We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do not send unsolicited commercial emails, because we hate spam as much as you do. By submitting your email address, you also agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display custom advertising to specific people who have opted-in to receive communications from us. Email addresses submitted only through the order processing page will be used for the sole purpose of sending you information and updates pertaining to your order. If, however, you have provided the same email to us through another method, we may use it for any of the purposes stated in this Policy. Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">Is the information collected through our service secure?</h2>
        <p>
        We take precautions to protect the security of your information. We have physical, electronic, and managerial procedures to help safeguard, prevent unauthorized access, maintain data security, and correctly use your information. However, neither people nor security systems are foolproof, including encryption systems. In addition, people can commit intentional crimes, make mistakes or fail to follow policies. Therefore, while we use reasonable efforts to protect your personal information, we cannot guarantee its absolute security. If applicable law imposes any non-disclaimable duty to protect your personal information, you agree that intentional misconduct will be the standards used to measure our compliance with that duty. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">Can I update or correct my information? </h2>
        <p>
            The rights you have to request updates or corrections to the information we collect depend on your relationship with us. Personnel may update or correct their information as detailed in our internal company employment policies. Customers have the right to request the restriction of certain uses and disclosures of personally identifiable information as follows. You can contact us in order to (1) update or correct your personally identifiable information, (2) change your preferences with respect to communications and other information you receive from us, or (3) delete the personally identifiable information maintained about you on our systems (subject to the following paragraph), by cancelling your account. Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion. To protect your privacy and security, we may take reasonable steps (such as requesting a unique password) to verify your identity before granting you profile access or making corrections. You are responsible for maintaining the secrecy of your unique password and account information at all times. You should be aware that it is not technologically possible to remove each and every record of the information you have provided to us from our system. The need to back up our systems to protect information from inadvertent loss means that a copy of your information may exist in a non-erasable form that will be difficult or impossible for us to locate. Promptly after receiving your request, all personal information stored in databases we actively use, and other readily searchable media will be updated, corrected, changed or deleted, as appropriate, as soon as and to the extent reasonably and technically practicable. If you are an end user and wish to update, delete, or receive any information we have about you, you may do so by contacting the organization of which you are a customer. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">Personnel </h2>
        <p>
        If you are one of our workers or applicants, we collect information you voluntarily provide to us. We use the information collected for Human Resources purposes in order to administer benefits to workers and screen applicants. You may contact us in order to (1) update or correct your information, (2) change your preferences with respect to communications and other information you receive from us, or (3) receive a record of the information we have relating to you. Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">Sale of Business</h2>
        <p>
        We reserve the right to transfer information to a third party in the event of a sale, merger or other transfer of all or substantially all of the assets of us or any of its Corporate Affiliates (as defined herein), or that portion of us or any of its Corporate Affiliates to which the Service relates, or in the event that we discontinue our business or file a petition or have filed against us a petition in bankruptcy, reorganization or similar proceeding, provided that the third party agrees to adhere to the terms of this Privacy Policy. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">Affiliates</h2>
        <p>
        We may disclose information (including personal information) about you to our Corporate Affiliates. For purposes of this Privacy Policy, "Corporate Affiliate" means any person or entity which directly or indirectly controls, is controlled by or is under common control with us, whether by ownership or otherwise. Any information relating to you that we provide to our Corporate Affiliates will be treated by those Corporate Affiliates in accordance with the terms of this Privacy Policy. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">How Long Do We Keep Your Information? </h2>
        <p>
        We keep your information only so long as we need it to provide service to you and fulfil the purposes described in this policy. This is also the case for anyone that we share your information with and who carries out services on our behalf. When we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory obligations, we'll either remove it from our systems or depersonalize it so that we can't identify you. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">How Do We Protect Your Information? </h2>
        <p>
        We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on file. We cannot, however, ensure or warrant the absolute security of any information you transmit to us or guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, technical, or managerial safeguards. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">Governing Law</h2>
        <p>
        The laws of the United States of America, excluding its conflicts of law rules, shall govern this Agreement and your use of our service. Your use of our service may also be subject to other local, state, national, or international laws.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">Your Consent</h2>
        <p>
        By using our service, registering an account, or making a purchase, you consent to this Privacy Policy.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">Links to Other Websites</h2>
        <p>
        This Privacy Policy applies only to the Services. The Services may contain links to other websites not operated or controlled by us. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">Cookies</h2>
        <p>
        We use "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to personalize the Content that you see on our website. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">Remarketing Services</h2>
        <p>
        We use remarketing services. What Is Remarketing? In digital marketing, remarketing (or retargeting) is the practice of serving ads across the internet to people who have already visited your website. It allows your company to seem like they're “following” people around the internet by serving ads on the websites and platforms they use most. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">Payment Details</h2>
        <p>
        In respect to any credit card or other payment processing details you have provided us, we commit that this confidential information will be stored in the most secure manner possible. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">Kids' Privacy</h2>
        <p>
        We collect information from kids under the age of 13 just to better our services. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data without your permission, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from our servers. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">Changes To Our Privacy Policy</h2>
        <p>
        If we decide to change our privacy policy, we will post those changes on this page, and/or update the Privacy Policy modification date below. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">Third-Party Services</h2>
        <p>
        We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third- Party Services"). <br /> <br/>
        You acknowledge and agree that we shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. We do not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.<br/><br/>
        Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.<br /><br/>
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">Tracking Technologies</h2>
        <p>
        The laws of the United States of America, excluding its conflicts of law rules, shall govern this Agreement and your use of our service. Your use of our service may also be subject to other local, state, national, or international laws.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">Tracking Technologies</h2>
        <h4 className="text-1xl font-bold mb-3">Cookie</h4>
        <p>
        We use Cookies to enhance the performance and functionality of our service but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit our service as we would not be able to remember that you had logged in previously. 
        </p><br/>
        <h4 className="text-1xl font-bold mb-3">Local Storage</h4>
        <p>
        Local Storage sometimes known as DOM storage, provides web apps with methods and protocols for storing client-side data. Web storage supports persistent data storage, similar to cookies but with a greatly enhanced capacity and no information stored in the HTTP request header. 
        </p><br />
        <h4 className="text-1xl font-bold mb-3">Sessions</h4>
        <p>
        uses "Sessions" to identify the areas of our website that you have visited. A Session is a small piece of data stored on your computer or mobile device by your web browser. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">Information about General Data Protection Regulation (GDPR) </h2>
        <p>
        We may be collecting and using information from you if you are from the European Economic Area (EEA), and in this section of our Privacy Policy we are going to explain exactly how and why is this data collected, and how we maintain this data under protection from being replicated or used in the wrong way. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">What is GDPR? </h2>
        <p>
        GDPR is an EU-wide privacy and data protection law that regulates how EU residents' data is protected by companies and enhances the control the EU residents have, over their personal data. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">What is personal data?</h2>
        <p>
        Any data that relates to an identifiable or identified individual. GDPR covers a broad spectrum of information that could be used on its own, or in combination with other pieces of information, to identify a person. Personal data extends beyond a person’s name or email address. Some examples include financial information, political opinions, genetic data, biometric data, IP addresses, physical address, sexual orientation, and ethnicity. 
        <br /><br />
        The Data Protection Principles include requirements such as:
        <br />
        Personal data collected must be processed in a fair, legal, and transparent way and should only be used in a way that a person would reasonably expect. 
        <br />
        Personal data should only be collected to fulfil a specific purpose and it should only be used for that purpose. Organizations must specify why they need the personal data when they collect it.
        </p>
        <br/> <br/>
        Personal data should be held no longer than necessary to fulfil its purpose.
        <br />
        People covered by the GDPR have the right to access their own personal data. They can also request a copy of their data, and that their data be updated, deleted, restricted, or moved to another organization. 
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">Why is GDPR important?</h2>
        <p>
        GDPR adds some new requirements regarding how companies should protect individuals' personal data that they collect and process. It also raises the stakes for compliance by increasing enforcement and imposing greater fines for breach. Beyond these facts it's simply the right thing to do. At Help Scout we strongly believe that your data privacy is very important and we already have solid security and privacy practices in place that go beyond the requirements of this new regulation. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">Individual Data Subject's Rights - Data Access, Portability and Deletion </h2>
        <p>
            We are committed to helping our customers meet the data subject rights requirements of GDPR. processes or stores all personal data in fully vetted, DPA compliant vendors. We do store all conversation and personal data for up to 6 years unless your account is deleted. In which case, we dispose of all data in accordance with our Terms of Service and Privacy Policy, but we will not hold it longer than 60 days. 
            <br/> <br/>
            We are aware that if you are working with EU customers, you need to be able to provide them with the ability to access, update, retrieve and remove personal data. We got you! We've been set up as self service from the start and have always given you access to your data and your customers data. Our customer support team is here for you to answer any questions you might have about working with the API. 
        </p>
      </section>

       {/* California Residents Section */}
       <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">California Residents</h2>
        <p>
          The California Consumer Privacy Act (CCPA) requires us to disclose categories of Personal Information we collect and how we use it. You may exercise the following rights:
        </p>
        <ul className="list-disc pl-8">
          <li>Right to Know and Access</li>
          <li>Right to Delete</li>
          <li>Right to Equal Service</li>
        </ul>
        <p>
          We do not sell the Personal Information of our users. For more information about these rights, please contact us.
        </p>
      </section>

      {/* California Online Privacy Protection Act (CalOPPA) Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">California Online Privacy Protection Act (CalOPPA)</h2>
        <p>
          CalOPPA requires us to disclose categories of Personal Information we collect and how we use it. CalOPPA users have the following rights:
        </p>
        <ul className="list-disc pl-8">
          <li>Right to Know and Access</li>
          <li>Right to Delete</li>
          <li>Right to Request that a Business Not Sell Data</li>
        </ul>
        <p>
          We do not sell the Personal Information of our users. For more information about these rights, please contact us.
        </p>
      </section>

      {/* Contact Us Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">Contact Us</h2>
        <p>If you have any questions, feel free to contact us at:</p>
        <p><strong>Email:</strong> info@quickapply.com</p>
      </section>




    </div>
  );
};

export default PrivacyPolicy;
