import React from 'react';

const TermsAndConditions: React.FC = () => {
  return (
    <div className="bg-white p-6 max-w-4xl mx-auto text-gray-800">

      {/* General Terms Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">1. General Terms</h2>
        <p className="mb-4">
          By accessing and placing an order with QuickApply (CLOUTRA), you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and QuickApply (CLOUTRA).
        </p>
        <p className="mb-4">
          Under no circumstances shall QuickApply (CLOUTRA) be liable for any direct, indirect, special, incidental, or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if QuickApply (CLOUTRA) team or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair, or correction of equipment or data, you assume any costs thereof.
        </p>
        <p>
          QuickApply (CLOUTRA) will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the right to change prices and revise the resources usage policy at any moment.
        </p>
      </section>

      {/* License Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">2. License</h2>
        <p>
          QuickApply (CLOUTRA) grants you a revocable, non-exclusive, non-transferable, limited license to download, install, and use the website strictly in accordance with the terms of this Agreement. These Terms & Conditions are a contract between you and QuickApply (CLOUTRA) ("we," "our," or "us") grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website strictly in accordance with the terms of this Agreement.
        </p>
      </section>

      {/* Definition and Key Terms Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">3. Definition and Key Terms</h2>
        <ul className="list-disc list-inside space-y-2">
          <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, and remember information about you such as your language preference or login information.</li>
          <li><strong>Company:</strong> when this policy mentions "Company," "we," "us," or "our," it refers to QuickApply (CLOUTRA) that is responsible for your information under this Privacy Policy.</li>
          <li><strong>Country:</strong> where QuickApply (CLOUTRA) or the owners/founders of QuickApply (CLOUTRA) are based, in this case is United States of America.</li>
          <li><strong>Customer:</strong> refers to the company, organization, or person that signs up to use the QuickApply (CLOUTRA) Service to manage the relationships with your consumers or service users.</li>
          <li><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit QuickApply (CLOUTRA) and use the services.</li>
          <li><strong>IP address:</strong> Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address.</li>
          <li><strong>Personnel:</strong> refers to those individuals who are employed by QuickApply (CLOUTRA) or are under contract to perform a service on behalf of one of the parties.</li>
          <li><strong>Personal Data:</strong> any information that directly, indirectly, or in connection with other information allows for the identification or identifiability of a natural person.</li>
          <li><strong>Service:</strong> refers to the service provided by QuickApply (CLOUTRA).</li>
          <li><strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
          <li><strong>Website:</strong> QuickApply (CLOUTRA)’s site, which can be accessed via this URL: <a href="https://quickapply.ai" className="text-blue-600 hover:underline">https://quickapply.ai</a>.</li>
          <li><strong>You:</strong> a person or entity that is registered with QuickApply (CLOUTRA) to use the Services.</li>
        </ul>
      </section>

       {/* User Registration Section */}
       <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">5. User Registration</h2>
        <p>
          You may be required to register with the Site. You agree to keep your password confidential and will be responsible for all use of your account and password. We reserve the right to remove, reclaim, or change a username you select if we determine, in our sole discretion, that such username is inappropriate, obscene, or otherwise objectionable.
        </p>
      </section>

      {/* Restrictions Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">6. Restrictions</h2>
        <p>You agree not to, and you will not permit others to:</p>
        <ul className="list-disc list-inside space-y-2">
          <li>License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the service or make the platform available to any third party.</li>
          <li>Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the service.</li>
          <li>Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of us or its affiliates, partners, suppliers or the licensors of the service.</li>
        </ul>
      </section>

      {/* Payment Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">6. Payment</h2>
        <p>
          If you register to any of our recurring payment plans, you agree to pay all fees or charges to your account for the Service in accordance with the fees, charges and billing terms in effect at the time that each fee or charge is due and payable. Unless otherwise indicated in an order form, you must provide us with a valid credit card (Visa, MasterCard, or any other issuer accepted by us) as a condition of signing up for the Premium plan.
        </p>
        <p>
          You agree to immediately notify us of any change in your billing address or the credit card used for payment hereunder. We reserve the right at any time to change its prices and billing methods, either immediately upon posting on our site or by email delivery to your organization’s administrator(s).
        </p>
      </section>

      {/* Free Trial Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">7. Free Trial</h2>
        <p>
          We offer a free trial to new users who register with the Site. Users can elect to purchase a package at the end of the free trial.
        </p>
      </section>

      {/* Cancellation Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">8. Cancellation</h2>
        <p>
          You can cancel your subscription at any time by contacting us using the contact information provided below. Your cancellation will take effect at the end of the current paid term. If you are unsatisfied with our services, please email us at info@quickapply.ai.
        </p>
      </section>

      {/* Prohibited Activities Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">9. Prohibited Activities</h2>
        <p>
          You may not access or use the Site for any purpose other than that for which we make the Site available. The Site may not be used in connection with any commercial endeavors except those that are specifically endorsed or approved by us. As a user of the Site, you agree not to:
        </p>
        <ul className="list-disc list-inside space-y-2">
          <li>Systematically retrieve data or other content from the Site to create or compile, directly or indirectly, a collection, compilation, database, or directory without written permission from us.</li>
          <li>Make any unauthorized use of the Site, including collecting usernames and/or email addresses of users by electronic or other means for the purpose of sending unsolicited email, or creating user accounts by automated means or under false pretenses.</li>
          <li>Use a buying agent or purchasing agent to make purchases on the Site.</li>
          <li>Use the Site to advertise or offer to sell goods and services.</li>
          <li>Circumvent, disable, or otherwise interfere with security-related features of the Site, including features that prevent or restrict the use or copying of any Content or enforce limitations on the use of the Site and/or the Content contained therein.</li>
          <li>Engage in unauthorized framing of or linking to the Site.</li>
          <li>Trick, defraud, or mislead us and other users, especially in any attempt to learn sensitive account information such as user passwords.</li>
          <li>Make improper use of our support services or submit false reports of abuse or misconduct.</li>
          <li>Engage in any automated use of the system, such as using scripts to send comments or messages, or using any data mining, robots, or similar data gathering and extraction tools.</li>
        </ul>
      </section>
       {/* User Generated Contributions Section */}
       <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">10. User Generated Contributions</h2>
        <p>
          The Site may invite you to chat, contribute to, or participate in blogs, message boards, online forums, and other functionality, and may provide you with the opportunity to create, submit, post, display, transmit, perform, publish, distribute, or broadcast content and materials to us or on the Site, including but not limited to text, writings, video, audio, photographs, graphics, comments, suggestions, or personal information or other material (collectively, "Contributions").
        </p>
        <p>
          Contributions may be viewable by other users of the Site and through third-party websites. As such, any Contributions you transmit may be treated as non-confidential and non-proprietary. When you create or make available any Contributions, you thereby represent and warrant that:
        </p>
        <ul className="list-disc list-inside space-y-2">
          <li>Your Contributions do not violate any applicable law, regulation, or rule.</li>
          <li>Your Contributions do not infringe any proprietary right, including but not limited to copyright, patent, trademark, trade secret, or moral right of any third party.</li>
          <li>Your Contributions are not obscene, lewd, lascivious, filthy, violent, harassing, or otherwise objectionable.</li>
          <li>Your Contributions do not violate the privacy or publicity rights of any third party.</li>
          <li>Your Contributions do not contain any offensive comments connected to race, national origin, gender, sexual preference, or physical handicap.</li>
          <li>Your Contributions do not violate any applicable law concerning child pornography or otherwise intended to protect the health or well-being of minors.</li>
        </ul>
      </section>

      {/* Contribution License Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">11. Contribution License</h2>
        <p>
          By posting your Contributions to any part of the Site, you automatically grant, and you represent and warrant that you have the right to grant, to us an unrestricted, unlimited, irrevocable, perpetual, non-exclusive, transferable, royalty-free, fully-paid, worldwide right and license to host, use, copy, reproduce, disclose, sell, resell, publish, broadcast, retitle, archive, store, cache, publicly perform, publicly display, reformat, translate, transmit, excerpt (in whole or in part), and distribute such Contributions (including, without limitation, your image and voice) for any purpose, commercial, advertising, or otherwise, and to prepare derivative works of, or incorporate into other works, such Contributions.
        </p>
      </section>

      {/* Guidelines for Reviews Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">12. Guidelines For Reviews</h2>
        <p>
          We may provide you areas on the Site to leave reviews or ratings. When posting a review, you must comply with the following criteria:
        </p>
        <ul className="list-disc list-inside space-y-2">
          <li>You should have firsthand experience with the person/entity being reviewed.</li>
          <li>Your reviews should not contain offensive profanity, or abusive, racist, offensive, or hate language.</li>
          <li>Your reviews should not contain discriminatory references based on religion, race, gender, national origin, age, marital status, sexual orientation, or disability.</li>
          <li>Your reviews should not contain references to illegal activity.</li>
          <li>You should not be affiliated with competitors if posting negative reviews.</li>
          <li>You should not make any conclusions as to the legality of conduct.</li>
        </ul>
      </section>

      {/* Your Suggestions Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">13. Your Suggestions</h2>
        <p>
          Any feedback, comments, ideas, improvements, or suggestions (collectively, "Suggestions") provided by you to us with respect to the site shall remain our sole and exclusive property. We shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or compensation to you.
        </p>
      </section>
      {/* Your Consent Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">14. Your Consent</h2>
        <p>
          By using our services, you agree to these terms and conditions, as well as any additional policies we may implement.
        </p>
      </section>

      {/* Links to Other Websites Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">15. Links to Other Websites</h2>
        <p>
          Our service may contain links to third-party websites or services that are not owned or controlled by us. We are not responsible for the content, privacy policies, or practices of any third-party websites.
        </p>
      </section>

      {/* Cookies Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">16. Cookies</h2>
        <p>
          We use cookies and similar tracking technologies to track the activity on our service and hold certain information. Cookies are files with a small amount of data that may include an anonymous unique identifier. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.
        </p>
      </section>

      {/* Changes to Our Terms & Conditions Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">17. Changes To Our Terms & Conditions</h2>
        <p>
          We may update our Terms & Conditions from time to time. We will notify you of any changes by posting the new Terms & Conditions on this page. You are advised to review this Terms & Conditions periodically for any changes.
        </p>
      </section>

      {/* Modifications to Our Service Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">18. Modifications to Our Service</h2>
        <p>
          We reserve the right to modify or discontinue, temporarily or permanently, our service or any features of it at any time without notice.
        </p>
      </section>

      {/* Governing Law Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">19. Governing Law</h2>
        <p>
          These Terms shall be governed and construed in accordance with the laws of the State, without regard to its conflict of law provisions.
        </p>
      </section>

      {/* Updates to Our Service Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">20. Updates to Our Service</h2>
        <p>
          We may release new tools and resources for our service, or introduce new services and/or features. Any new features or services shall be subject to the terms and conditions outlined herein.
        </p>
      </section>

      {/* Third-Party Services Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">21. Third-Party Services</h2>
        <p>
          We may utilize third-party services such as analytics providers, advertisers, or other services to help us deliver, analyze, and improve our service. You acknowledge that these third-party services are governed by their own terms of service and privacy policies.
        </p>
      </section>

      {/* Term and Termination Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">22. Term and Termination</h2>
        <p>
          We reserve the right to terminate or suspend your account or access to our service at any time, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the terms.
        </p>
      </section>

      {/* Copyright Infringement Notice Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">23. Copyright Infringement Notice</h2>
        <p>
          If you believe that your copyrighted work has been copied in a way that constitutes copyright infringement, please provide us with the following information: your contact details, a description of the copyrighted work, and a statement that you have a good faith belief that the disputed use is not authorized by the copyright owner.
        </p>
      </section>

      {/* Indemnification Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">24. Indemnification</h2>
        <p>
          You agree to indemnify, defend, and hold harmless us, our affiliates, officers, directors, agents, employees, and contractors from and against any and all claims, damages, liabilities, losses, and expenses arising from or related to your use of our services or your violation of these terms.
        </p>
      </section>

      {/* User Data Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">25. User Data</h2>
        <p>
          We will maintain certain data that you transmit to the service for the purpose of managing the service’s performance, as well as data relating to your use of the service. You are solely responsible for all data that you transmit or that relates to any activity you have undertaken using the service.
        </p>
      </section>

      {/* Electronic Communications, Transactions, and Signatures Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">26. Electronic Communications, Transactions, And Signatures</h2>
        <p>
            Visiting the Site, sending us emails, and completing online forms constitute electronic communications. You consent to receive electronic communications, and you agree that all agreements, notices, disclosures, and other communications we provide to you electronically, via email and on the Site, satisfy any legal requirement that such communication be in writing.   
        </p>
        <br />
        <p>
        YOU HEREBY AGREE TO THE USE OF ELECTRONIC SIGNATURES, CONTRACTS, ORDERS, AND OTHER RECORDS, AND TO ELECTRONIC DELIVERY OF NOTICES, POLICIES, AND RECORDS OF TRANSACTIONS INITIATED OR COMPLETED BY US OR VIA THE SITE. You hereby waive any rights or requirements under any statutes, regulations, rules, ordinances, or other laws in any jurisdiction which require an original signature or delivery or retention of non-electronic records, or to payments or the granting of credits by any means other than electronic means.   
        </p>
      </section>
      {/* Texas Users and Residents Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">27. Texas Users And Residents</h2>
        <p>
          If any complaint with us is not satisfactorily resolved, you can contact:
        </p>
        <ul className="list-disc pl-8">
          <li>Texas Department of Consumer Affairs</li>
          <li>Complaint Assistance Unit</li>
          <li>123 Address Lane, Austin, TX, USA</li>
          <li>Phone: (123) 456-7890</li>
        </ul>
      </section>

      {/* No Warranties Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">28. No Warranties</h2>
        <p>
          Our service is provided "as is" without any warranties of any kind, either express or implied. We do not guarantee that the service will be uninterrupted or error-free, and we disclaim any warranties of merchantability, fitness for a particular purpose, or non-infringement.
        </p>
      </section>

      {/* Limitation of Liability Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">29. Limitation of Liability</h2>
        <p>
          In no event shall we, our officers, directors, employees, or agents be liable to you for any indirect, incidental, special, punitive, or consequential damages arising out of or related to your use of the service, whether based in contract, tort, strict liability, or otherwise.
        </p>
      </section>

      {/* Severability Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">30. Severability</h2>
        <p>
          If any provision of this agreement is deemed unlawful, void, or unenforceable, that provision shall be deemed severable from this agreement and shall not affect the validity and enforceability of any remaining provisions.
        </p>
      </section>

      {/* Waiver Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">31. Waiver</h2>
        <p>
          Our failure to enforce any right or provision of these terms will not be considered a waiver of those rights. If any provision of these terms is found to be invalid or unenforceable, the remaining provisions will remain in effect.
        </p>
      </section>

      {/* Amendments to this Agreement Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">32. Amendments to this Agreement</h2>
        <p>
          We reserve the right to modify these terms at any time. You are responsible for regularly reviewing these terms. Your continued use of our service after any modification constitutes your acceptance of the revised terms.
        </p>
      </section>

      {/* Entire Agreement Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">33. Entire Agreement</h2>
        <p>
          These terms constitute the entire agreement between us regarding our service and supersede and replace any prior agreements we might have had regarding the service.
        </p>
      </section>

      {/* Updates to Our Terms Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">34. Updates to Our Terms</h2>
        <p>
          We may update these terms and conditions periodically. If we make material changes, we will notify you either through email or by placing a prominent notice on our website.
        </p>
      </section>

      {/* Intellectual Property Section */}
      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">35. Intellectual Property</h2>
        <p>
          Our service and its entire contents, features, and functionality are and will remain the exclusive property of us and our licensors. The service is protected by copyright, trademark, and other laws of the state, country, or other relevant jurisdictions.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">36. Agreement to Arbitrate</h2>
        <p>
            This section applies to any dispute EXCEPT IT DOESN’T INCLUDE A DISPUTE RELATING TO CLAIMS FOR INJUNCTIVE OR EQUITABLE RELIEF REGARDING THE ENFORCEMENT OR VALIDITY OF YOUR OR ’s INTELLECTUAL PROPERTY RIGHTS. The term “dispute” means any dispute, action, or other controversy between you and us concerning the Services or this agreement, whether in contract, warranty, tort, statute, regulation, ordinance, or any other legal or equitable basis. “Dispute” will be given the broadest possible meaning allowable under law. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">37. Notice of Dispute </h2>
        <p>
        In the event of a dispute, you or us must give the other a Notice of Dispute, which is a written statement that sets forth the name, address, and contact information of the party giving it, the facts giving rise to the dispute, and the relief requested. You must send any Notice of Dispute via email to: info@quickapply.ai. We will send any Notice of Dispute to you by mail to your address if we have it, or otherwise to your email address. You and us will attempt to resolve any dispute through informal negotiation within sixty (60) days from the date the Notice of Dispute is sent. After sixty (60) days, you or us may commence arbitration. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">38. Binding Arbitration </h2>
        <p>
        If you and us don’t resolve any dispute by informal negotiation, any other effort to resolve the dispute will be conducted exclusively by binding arbitration as described in this section. You are giving up the right to litigate (or participate in as a party or class member) all disputes in court before a judge or jury. The dispute shall be settled by binding arbitration in accordance with the commercial arbitration rules of the American Arbitration Association. Either party may seek any interim or preliminary injunctive relief from any court of competent jurisdiction, as necessary to protect the party’s rights or property pending the completion of arbitration. Any and all legal, accounting, and other costs, fees, and expenses incurred by the prevailing party shall be borne by the non-prevailing party. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">39. Submissions and Privacy </h2>
        <p>
        If you submit or post any ideas, creative suggestions, designs, photographs, information, advertisements, data or proposals, including ideas for new or improved products, services, features, technologies or promotions, you expressly agree that such submissions will automatically be treated as non- confidential and non-proprietary and will become the sole property of us without any compensation or credit to you whatsoever. We and our affiliates shall have no obligations with respect to such submissions or posts and may use the ideas contained in such submissions or posts for any purposes in any medium in perpetuity, including, but not limited to, developing, manufacturing, and marketing products and services using such ideas. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">40. Advertisers</h2>
        <p>
        We allow advertisers to display their advertisements and other information in certain areas of the Site, such as sidebar advertisements or banner advertisements. If you are an advertiser, you shall take full responsibility for any advertisements you place on the Site and any services provided on the Site or products sold through those advertisements. Further, as an advertiser, you warrant and represent that you possess all rights and authority to place advertisements on the Site, including, but not limited to, intellectual property rights, publicity rights, and contractual rights. We simply provide the space to place such advertisements, and we have no other relationship with advertisers. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">41. U.S. Government Rights </h2>
        <p>
        Our services are “commercial items” as defined in Federal Acquisition Regulation (“FAR”) 2.101. If our services are acquired by or on behalf of any agency not within the Department of Defense (“DOD”), our services are subject to the terms of these Terms of Use in accordance with FAR 12.212 (for computer software) and FAR 12.211 (for technical data). If our services are acquired by or on behalf of any agency within the Department of Defense, our services are subject to the terms of these Terms of Use in accordance with Defense Federal Acquisition Regulation (“DFARS”) 227.72023. In addition, DFARS 252.2277015 applies to technical data acquired by the DOD. This U.S. Government Rights clause is in lieu of, and supersedes, any other FAR, DFARS, or other clause or provision that addresses government rights in computer software or technical data under these Terms of Use. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">42. Site Management</h2>
        <p>
        We reserve the right, but not the obligation, to: (1) monitor the Site for violations of these Terms of Use; (2) take appropriate legal action against anyone who, in our sole discretion, violates the law or these Terms of Use, including without limitation, reporting such user to law enforcement authorities; (3) in our sole discretion and without limitation, refuse, restrict access to, limit the availability of, or disable (to the extent technologically feasible) any of your Contributions or any portion thereof; (4) in our sole discretion and without limitation, notice, or liability, to remove from the Site or otherwise disable all files and content that are excessive in size or are in any way burdensome to our systems; and (5) otherwise manage the Site in a manner designed to protect our rights and property and to facilitate the proper functioning of the Site. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">43. Promotions</h2>
        <p>
        We may, from time to time, include contests, promotions, sweepstakes, or other activities (“Promotions”) that require you to submit material or information concerning yourself. Please note that all Promotions may be governed by separate rules that may contain certain eligibility requirements, such as restrictions as to age and geographic location. You are responsible to read all Promotions rules to determine whether or not you are eligible to participate. If you enter any Promotion, you agree to abide by and to comply with all Promotions Rules. Additional terms and conditions may apply to purchases of goods or services on or through the Services, which terms and conditions are made a part of this Agreement by this reference. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">44. Typographical Errors </h2>
        <p>
        In the event a product and/or service is listed at an incorrect price or with incorrect information due to typographical error, we shall have the right to refuse or cancel any orders placed for the product and/ or service listed at the incorrect price. We shall have the right to refuse or cancel any such order whether or not the order has been confirmed and your credit card charged. If your credit card has already been charged for the purchase and your order is cancelled, we shall immediately issue a credit to your credit card account or other payment account in the amount of the charge. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">45. Miscellaneous </h2>
        <p>
        If for any reason a court of competent jurisdiction finds any provision or portion of these Terms & Conditions to be unenforceable, the remainder of these Terms & Conditions will continue in full force and effect. Any waiver of any provision of these Terms & Conditions will be effective only if in writing and signed by an authorized representative of us. We will be entitled to injunctive or other equitable relief (without the obligations of posting any bond or surety) in the event of any breach or anticipatory breach by you. We operate and control our Service from our offices in U.S. The Service is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation. Accordingly, those persons who choose to access our Service from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable. These Terms & Conditions (which include and incorporate our Privacy Policy) contains the entire understanding, and supersedes all prior understandings, between you and us concerning its subject matter, and cannot be changed or modified by you. The section headings used in this Agreement are for convenience only and will not be given any legal import. 
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">46. Disclaimer </h2>
        <p>
            We are not responsible for any content, code or any other imprecision. We do not provide warranties or guarantees. In no event shall we be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. We reserve the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.
        </p>
        <br />
        <p>
        Our Service and its contents are provided "as is" and "as available" without any warranty or representations of any kind, whether express or implied. We are a distributor and not a publisher of the content supplied by third parties; as such, our exercises no editorial control over such content and makes no warranty or representation as to the accuracy, reliability or currency of any information, content, service or merchandise provided through or accessible via our Service. Without limiting the foregoing, We specifically disclaim all warranties and representations in any content transmitted on or in connection with our Service or on sites that may appear as links on our Service, or in the products provided as a part of, or otherwise in connection with, our Service, including without limitation any warranties of merchantability, fitness for a particular purpose or non-infringement of third party rights. No oral advice or written information given by us or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty. Price and availability information is subject to change without notice. Without limiting the foregoing, we do not warrant that our Service will be uninterrupted, uncorrupted, timely, or error-free. 
        </p>
      </section>

        
    <section className="mb-8">
        <h2 className="text-3xl font-bold mb-6">47. Contact Us</h2>
        <p>Don't hesitate to contact us if you have any questions.</p>
        <p className="mr-1">
            - Via Email: 
            <a className="text-blue-500 hover:underline" href="mailto:info@quickapply.com">
             info@quickapply.com
            </a>
        </p>
    </section>




      {/* Additional sections can be added here in a similar structure */}
    </div>
  );
};

export default TermsAndConditions;
